name: "pipeline-trigger"
description: "Triggers a workflow in another repository and posts results in the pull request comments"
inputs:
  pat-token:
    description: "Personal Access Token (PAT) for the repository initiating the workflow"
    required: true
  owner:
    description: "Owner of the target repository where the workflow will be triggered"
    required: true
  repo:
    description: "Target repository where the workflow will be triggered"
    required: true
outputs:
  message:
    description: "Execution result of the triggered pipeline"
runs:
  using: "node20"
  main: "dist/index.js"